group: travis_latest
language: node_js
node_js: node
cache: yarn
env:
  global:
  - secure: IMLCUj+EPYOkZ1juqycQ7527YdK8NMFlwoj4yYupz0WS70ItufC53DNqtwmqKRcy5W2DYdxzgdGGChDfnvluqaV7MOS0j1x/XwZGXyJVbov2Krdh2yq4lIp8dvLiZ0n1b6/SyCczQhol76Rl0bkZ9DcKM28C1gfOBnCP6aEbDDAiNLuwjKsqgvEZQySUDEFlLtM7KTYoL9m8odArNoo6d5OWdQTYsd3M5yYNIYo9ZR9YVsSO/40AWuCpvwPfhxwmeakcQ3FjcccJKEqdTJf2RCL3EIOPo6VK7V5EtpoNTlAQiB5iWqy3W6SgCPkAcgAvcFZvJj3J06VlHH8J1ZOzUl6aw2B6SyJSz8Wp43WQMNkDm8VAQfGb7/xonZKy/Pb/YCU+TGnmmkxbhgvDPJXChpL/HYKYXjMShnIAHOZRReCD9oc9kgX3ZrNU4dFkF/a+FSyYYQt85byq8xsuimutBlFJESYKcHgvpaUycibB0NHAM0Pb4A0SFjGsRQHbZYIIiudGBbb3JYa2/7CVEbFw8Ig3F9kxJld4jxDLA2/LtO9OLRwRmrTaKcJ9L/80S6QtGdvstl8J9c97akcDhc6SGkKMC8UJMFptJsa1XcgBlWA3EqezyvuneSSeiu+6XFTZKC21bpbQF2dGJM3YLWhwYxoYOTqS21jGMWA8PiyUx/w=
  - secure: 0HxfQvgD0lcwFxpma2UAPJj0A7zQ/QFMmApm7/sqyb6BbnvlO00ZTX2ejXfwxb5nxa4HVdBwJ81YbBLoDTXh+WCC740/31ipbPnxAqLdF02xUZ1B6yrmf/eipJzRg9ZOjY+Iw+56WzSxNbOZ4oJI5devonhUZDqCvj1iA0TzMAaxjrVTWyFO5+47MV1ZVUqQIb7PUciWRAOq+u0W76G5B9rES53G9MRPt0Cvy8v5xlfaJWxSYuDBnxVsYz5MyZERMODsvfMoqCo+uqDpSCYQV0JR+xxXYasKKC1+B+v8CtSQJxP5+5Nry6coA4zaq2xy5HS6YpH+TrUYiBXRkqpjTUGbFu88LEXyu6hfMWqC/ETwsgRk+G/WB7G68DUMrSGhFmqPWmYom+bLbImROWiTPS1z0lfWOFbHZcGZmSNx15j983rJIC23KaZ38oL35mg4IflbS/EWlZVNTb83nJBZbNzQR4Qyb12xR+mPZVlha3DX5yOm7ZuVs7wJctX5zGy5GgwxerNzDZCzo0TS5DaG59vBug0Ioct5goVKRKFgUyAXB8D8my6P16+jDW1a3RjPiR3EPj5zXfbQQUhneetxWG89fFd5xaftDKrda4sgPm9cQyRAKJZdk0tHijNt10trnErBTVYrbI7mJt5U0JVQcWAOPW69O6SXUbhMmOjMLuM=
branches:
  only:
    - master
deploy:
  provider: script
  skip_cleanup: true
  script:
  - yarn release
